---
- name: "Process the osdk-scorecard template"
  template:
    src: "osdk-scorecard.yml.j2"
    dest: "{{ work_dir }}/osdk-scorecard.yml"

- name: "Run operator-sdk scorecard tests on the deployed operator in json form"
  shell: "{{ operator_sdk_bin_path }} scorecard --version=v1alpha2 --verbose --config {{ work_dir }}/osdk-scorecard.yml > {{ work_dir }}/{{ cr_kind }}-{{ cr_name }}-scorecard-results.json 2> {{ work_dir}}/{{ cr_name }}-scorecard-errors.txt"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  ignore_errors: true

- name: "Parse json operator scorecard results"
  shell: "cat {{ work_dir }}/{{ cr_kind }}-{{ cr_name }}-scorecard-results.json | {{ jq_bin_path }} '.results[] | select(.labels.suite == \"basic\") | select(.state == \"pass\").name' | wc -l"
  register: scorecard_results_passed_result

- debug:
    msg: "Scorecard Basic Tests passed: {{ scorecard_results_passed_result.stdout }}"
